
package org.locationscout.locations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocationCatalogService", targetNamespace = "http://locations.locationscout.org/", wsdlLocation = "http://localhost:8080/LocationScout/LocationCatalogService?wsdl")
public class LocationCatalogService
    extends Service
{

    private final static URL LOCATIONCATALOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCATIONCATALOGSERVICE_EXCEPTION;
    private final static QName LOCATIONCATALOGSERVICE_QNAME = new QName("http://locations.locationscout.org/", "LocationCatalogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LocationScout/LocationCatalogService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCATIONCATALOGSERVICE_WSDL_LOCATION = url;
        LOCATIONCATALOGSERVICE_EXCEPTION = e;
    }

    public LocationCatalogService() {
        super(__getWsdlLocation(), LOCATIONCATALOGSERVICE_QNAME);
    }

    public LocationCatalogService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCATIONCATALOGSERVICE_QNAME, features);
    }

    public LocationCatalogService(URL wsdlLocation) {
        super(wsdlLocation, LOCATIONCATALOGSERVICE_QNAME);
    }

    public LocationCatalogService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCATIONCATALOGSERVICE_QNAME, features);
    }

    public LocationCatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationCatalogService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocationCatalog
     */
    @WebEndpoint(name = "LocationCatalogPort")
    public LocationCatalog getLocationCatalogPort() {
        return super.getPort(new QName("http://locations.locationscout.org/", "LocationCatalogPort"), LocationCatalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationCatalog
     */
    @WebEndpoint(name = "LocationCatalogPort")
    public LocationCatalog getLocationCatalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://locations.locationscout.org/", "LocationCatalogPort"), LocationCatalog.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCATIONCATALOGSERVICE_EXCEPTION!= null) {
            throw LOCATIONCATALOGSERVICE_EXCEPTION;
        }
        return LOCATIONCATALOGSERVICE_WSDL_LOCATION;
    }

}
